services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - 5173:5173
    networks:
      - react-express 
    environment:
      REACT_APP_API_URL= http://backend:5050
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    networks:
      - express-mongo
      - react-express 
    depends_on:
      - mongo
    expose:
      - 5050

  mongo:
    restart: always
    image: mongo:latest
    networks:
      - express-mongo 
    volumes:
      - mongo-data:/data/db
    expose:
      - 27017

  networks:
    express-mongo: 
      driver: bridge
    react-express:
      driver: bridge

  volumes:
    mongo-data:
      driver: local
